### ISSUE TITLE
Mapping non-standard MIDI Range params

### ISSUE THREAD

**Issue by lennart** [tidalcycles/tidal-midi#1]
In my portmidi fork, I generalized the MIDI interface so one can write additional synth mappings without the boilerplate. (Actually I added a new _shape_ `ControllerShape` to define MIDI Synths, that can be converted `toOscShape` which is given to the various makeF calls in the Synth definition.)

However I am currently struggling on how to generalize parameter range mapping, as many synths have CC params (or NRPN/SysEx) that do not range from 0..127 but rather have custom ranges (0..5, simply 0 or 1, or in the case of NRPN even negative ranges -127..127).

The idea should be to not have to specify the _default_ range of 0..127 for simple mappings, still a "range" should be an optional value for the constructor of a shape param, I am not sure how to do this with Haskell data types without having to pattern match against the "optional" range.

Any suggestions? If this is solved, I guess the portmidi fork just needs some testing and should be ready for merging into master (as of now it adds: cross-platform compat, multi-channel access and NRPN communication)

**Comment by kindohm** [comment]
Lennart - I hope to give your latest code a try later today after work. I'm
mainly interested to see how the new timing works. What do you mean by
"additional synth mappings"?

-Mike

**Comment by kindohm** [comment]
A bit off topic, but what does this mean:

> I generalized the MIDI interface so one can write additional synth mappings without the boilerplate

**Comment by lennart** [comment]
Sorry if this is unclear, this just refers to having a module in Tidal MIDI that contains all the MIDI sending internals and keyproxing functions, so you can write your synth mappings without having to define something like `keyproxy` or `makeCtrl`, `noteOn` etc. over and over again.

Synth mappings now just have to include `ControllerShape` and the necessary `makeF` calls to make your own functions.

I did not by any means generalize MIDI ;)

**Comment by lennart** [comment]
this seems solved and is pretty old...the mentioned functionality is somehow superseeded partially by what tidal-core does now.
