### ISSUE TITLE
midiproxy not defined since the version 0.8

### ISSUE THREAD

**Issue by fp4me** [tidalcycles/tidal-midi#11]
Hi, the midiproxy function have disappeared from the new 0.8 package.

**Comment by yaxu** [comment]
That's not needed any more, are you following the instructions here? http://tidalcycles.org/howtos.html#midi

**Comment by fp4me** [comment]
Oh sorry , i have try the new instructions but now i have a segmentation fault with the PortMidi package on windows / 64 bits... 
I will try with an haskell platform in 32bits.
Thank you for your great job on Tidal !
