### ISSUE TITLE
error when trying to play notes: "Couldn't match type 'Pattern ParamMap'"

### ISSUE THREAD

**Issue by cornedriesprong** [tidalcycles/tidal-midi#26]
Hi,

I'm trying to get Tidal to play MIDI. I've followed the instructions in the readme and everything seems to work except when I evaluate a command to play a note I get the following error:

`Couldn't match type 'Pattern ParamMap' with 'tidal-0.8:Sound.Tidal.Pattern.Pattern tidal-0.8:Sound.Tidal.Stream.ParamMap'`

My code:
```
import Sound.Tidal.MIDI.Context

devices <- midiDevices

m1 <- midiStream devices "Bus 1" 1 synthController

m1 $ note "0"
```

Any ideas?

**Comment by lennart** [comment]
tidal-midi installs tidal == 0.8 whereas `cabal install tidal` will install tidal == 0.8.2

Run `ghc-pkg list tidal` and `ghc-pkg list tidal-midi`. this should tell you that you have **two** versions of tidal installed, but you should always stick to have only **one** version of tidal installed at once, right now.

you can simply do `ghc-pkg unregister tidal-0.8.2` and use tidal-0.8 with tidal-midi-0.8.

we haven't yet release tidal-midi 0.8.1 which shall depend on tidal 0.8.2. (latest master here should work, so you can clone the repo and do a `cabal install` from within source, be sure to remove all of both tidal and tidal-midi versions beforehand)

hope this helps!

**Comment by yaxu** [comment]
Are we ready to release tidal-midi 0.8.1? Just needs a bump to the version field tidal-midi.cabal updated, and uploaded to hackage?

**Comment by lennart** [comment]
I think we are, travis says this should build so, yes we'd need to do what you describe (later today?) @yaxu 

however, @cornedriesprong  did this fix your issues?

**Comment by cornedriesprong** [comment]
@lennart I've unregistered tidal 0.8.2 and it works now! thanks for your help!

**Comment by lennart** [comment]
@cornedriesprong great to hear! @yaxu released a new tidal-midi version, so you should now be able to run latest tidal midi with tidal 0.8.2 after: `cabal update && cabal install tidal-midi` and a restart of your editor environment for tidal.
